version: "3.9"

services:

  postgres:
    image: postgres:18


    container_name: watchmate-db

    restart: always

    environment:
      POSTGRES_DB:  postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  backend:

    build:
      context: ./backend/watchmate

    container_name: watchmate-backend

    restart: always

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - postgres

  frontend:

    build:
      context: ./frontend

    container_name: watchmate-frontend

    restart: always
    
    ports:
      - "3000:80"

    depends_on:
      - backend

volumes:
  postgres_data: